config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'page/home'

  get 'page/about_us'

  get 'page/events'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IosClubSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="wrapper">
        <header>
             <h1> iOS Club </h1>
        </header>
    <nav>
    <div id="nav">
      <ul>
        <li> <%= link_to 'Home', page_home_path %></li>
        <li> <%= link_to 'About Us', page_about_us_path %></li>
      </ul>
    </div>
  </nav>

<%= yield %>

   </div>

</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/events.html.erb
<h1>Page#events</h1>
<p>Find me in app/views/page/events.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

<div id="container">
  <img  src="images/img1.png" id="img"/>
  <div id="left_holder">
    <img onClick="slide(-1)" class="left" src="app/assets/images/left_arrow.png"/>
  </div>
  <div id="right_holder">
    <img onClick="slide(1)" class="right" src="app/assets/images/right_arrow.png"/>
  </div>
</div>